PSOVDF3 ;BIR/RTR-OUTPATIENT PHARMACY VDEF MESSAGE CONTINUED ;06/16/05
 ;;7.0;OUTPATIENT PHARMACY;**205,235**;DEC 1997
 ;
 ;External refernce to PS(50.607 supported by DBIA 2221
 ;
DOSE(GLOBAL) ;Add Dosage information to RXE 1
 N RES S RES=""
 N PSODD1,PSODD2,PSODD3,PSODD5,PSODDL,PSODDN,PSORES1,PSODDUNT,PSOD1FLG
 F PSODDL=0:0 S PSODDL=$O(GLOBAL(PSODDL)) Q:'PSODDL  D
 .S PSODDN=$G(GLOBAL(PSODDL,0)) Q:PSODDN=""
 .S PSODD1=$P(PSODDN,"^"),PSODD2=$P(PSODDN,"^",2),PSODD3=$P(PSODDN,"^",3),PSODD5=$P(PSODDN,"^",5),PSODDUNT=""
 .I PSODD1="",PSODD2="",PSODD5="" Q
 .I PSODD5'="",($E(PSODD5,$L(PSODD5))'?1A) S PSODD5=PSODD5_"D"
 .I PSODD5'="" S PSODD5=$$REPL^PSOVDF1(PSODD5)
 .S PSOD1FLG=0
 .I PSODD2'="",PSODD3'="",$P($G(^PS(50.607,PSODD3,0)),"^")'="" S PSOD1FLG=1,PSODDUNT=$P($G(^(0)),"^"),PSODDUNT=$$REPL^PSOVDF1(PSODDUNT) S:$G(PSODD1)'="" PSODD1=$$REPL^PSOVDF1(PSODD1),PSODD1=PSODD1_PSODDUNT
 .I 'PSOD1FLG,$G(PSODD1)'="" S PSODD1=$$REPL^PSOVDF1(PSODD1)
 .S PSORES1=""
 .I PSODD1'=""!(PSODD2'="") D
 ..I PSODD2'="" S PSODD2=$$REPL^PSOVDF1(PSODD2) S PSORES1=PSODD2 S:PSODD1'="" PSORES1=PSORES1_SEPS_PSODD1 Q
 ..S PSORES1=SEPS_PSODD1
 .I PSODD5'="" D
 ..I PSORES1="" S PSORES1=SEPC_SEPC_PSODD5 Q
 ..S PSORES1=PSORES1_SEPC_SEPC_PSODD5
 .Q:PSORES1=""
 .I $G(RES)'="" S RES=RES_SEPR_PSORES1 Q
 .S RES=PSORES1
 K TEMP
 Q RES
 ;
FINISH ;Finish rest of RXE 1 segment
 N PSOVAL1 S PSOVAL1=$P(VAL,SEPR)
 S WR=""
 S WR=$$GET^PSOVDF2(.GL,2,2)
 I $G(WR)'="" S WR=$$HLDATE^HLFNC(WR,"TS") I WR>0 S WR=$$REPL^PSOVDF1(WR),$P(PSOVAL1,SEPC,4)=WR,$P(PSOVAL1,SEPC,7)="FILL"
 ; (1~5-26.1)
 S WR=$$GET^PSOVDF2(.GL,3,5)
 I $G(WR)'="" D
 .S WR=$$HLDATE^HLFNC(WR,"TS") I WR>0 S WR=$$REPL^PSOVDF1(WR),$P(PSOVAL1,SEPC,5)=WR,$P(PSOVAL1,SEPC,7)=$P(PSOVAL1,SEPC,7)_"/CANCEL"
 E  S WR=$$GET^PSOVDF2(.GL,2,6) I $G(WR)'="" D
 .  S WR=$$HLDATE^HLFNC(WR,"TS") I WR>0 S WR=$$REPL^PSOVDF1(WR),$P(PSOVAL1,SEPC,5)=WR,$P(PSOVAL1,SEPC,7)=$P(PSOVAL1,SEPC,7)_"/EXPIRATION"
 S $P(VAL,SEPR)=PSOVAL1
 S WR=""
 Q
 ;
REM ;Remarks for Original Fill
 S MSG="",CTR=0
 S VAL=$$GET^PSOVDF2(.GL,3,7)
 I $G(VAL)="" Q
 S VAL=$$REPL^PSOVDF1(VAL)
 D PUT(3)
 S CTR=CTR+1,VAL=CTR D PUT(1)
 S VAL="RE"_SEPC_"REMARKS"_SEPC_SRC_"_12" D PUT(4)
 S MSG="NTE"_SEPF_MSG D OUT^PSOVDF2
 Q
 ;
DEL ;Deletion comments
 S MSG=""
 S VAL=$$GET^PSOVDF2(.GL,"D",1)
 I $G(VAL)="" Q
 S VAL=$$REPL^PSOVDF1(VAL)
 D PUT(3)
 S CTR=CTR+1,VAL=CTR D PUT(1)
 S VAL="DE"_SEPC_"DELETION COMMENTS"_SEPC_SRC_"_108" D PUT(4)
 S MSG="NTE"_SEPF_MSG D OUT^PSOVDF2
 Q
 ;
CLOZ ; Clozapine Dosage
 S VAL=$$REPL^PSOVDF1(VAL)
 D PUT(5)
 S CTR=CTR+1,VAL=CTR D PUT(1)
 S VAL="NM" D PUT(2)
 S VAL="CLOZAPINE DOSAGE" D PUT(3)
 S VAL="MG/DAY" D PUT(6)
 S VAL="F" D PUT(11)
 S MSG="OBX"_SEPF_MSG D OUT^PSOVDF2
 Q
 ;
WBC ; WBC results
 S VAL=$$REPL^PSOVDF1(VAL)
 D PUT(5)
 S CTR=CTR+1,VAL=CTR D PUT(1)
 S VAL="NM" D PUT(2)
 S VAL="WBC RESULTS" D PUT(3)
 S VAL="F" D PUT(11)
 ; (14-303)
 S VAL=$$GET^PSOVDF2(.GL,"SAND",3)
 I $G(VAL)'="" S VAL=$$HLDATE^HLFNC(VAL,"TS") I VAL>0 S VAL=$$REPL^PSOVDF1(VAL) D PUT(14)
 S MSG="OBX"_SEPF_MSG D OUT^PSOVDF2
 Q
PRC ;Provider Comments, do not piece out data, can contain up-arrow
 S MSG=""
 I '$D(GL("PRC")) Q
 S VAL="" K TEMP M TEMP=GL("PRC") S VAL=$$SSETZ(.TEMP,1)
 I $G(VAL)="" Q
 D PUT(3)
 S CTR=CTR+1,VAL=CTR D PUT(1)
 S VAL="PR"_SEPC_"PROVIDER COMMENTS"_SEPC_HLINST_"_52.039_.01" D PUT(4)
 S MSG="NTE"_SEPF_MSG D OUT^PSOVDF2
 Q
SSETZ(GLOBAL,P) ;Format Provider Comments
 N RES,PSOVPCOM,PSOVDFD1,X
 S (RES,X)="",PSOVDFD1=0
SSET10Z S PSOVDFD1=$O(GLOBAL(PSOVDFD1)) G SSETQZ:'PSOVDFD1
 S PSOVPCOM=GLOBAL(PSOVDFD1,0) I PSOVPCOM="" G SSET10Z
 I $G(RES)'="" S RES=RES_" "_PSOVPCOM
 E  S RES=PSOVPCOM
 G SSET10Z
SSETQZ ;
 I $G(RES)'="" S RES=$$REPL^PSOVDF1(RES)
 Q RES
 ;
 Q
 ;
PUT(P) ; Put in MSG
 I $G(VAL)="" Q
 S $P(MSG,SEPF,P)=VAL
 Q
 ;
SSET(GLOBAL,P,L) ;Schedule field
 N RES,PSOVSCH,PSOVDFD1,X
 S (RES,X)="",PSOVDFD1=0
SSET10 S PSOVDFD1=$O(GLOBAL(PSOVDFD1)) G SSETQ:'PSOVDFD1
 I $G(L)="" S L=""
 S X=$G(GLOBAL(PSOVDFD1,0)) S PSOVSCH=$P($G(X),U,P),PSOVSCH=$$REPL^PSOVDF1(PSOVSCH) I PSOVSCH'="" D
 .I $G(RES)'="" S RES=RES_SEPR_PSOVSCH_SEPC_SEPC_L
 .E  S RES=PSOVSCH_SEPC_SEPC_L
 .S CTR=CTR+1
 G SSET10
SSETQ ;
 Q RES
 ;
 Q
 ;
SSETX(GLOBAL,P,L) ;Format Sig, don't piece out, can possibly contain up-arrow from Provider Comments
 N RES,PSOVSIG,PSOVDFD1,X
 S (RES,X)="",PSOVDFD1=0
SSET10X S PSOVDFD1=$O(GLOBAL(PSOVDFD1)) G SSETQX:'PSOVDFD1
 I $G(L)="" S L=""
 S PSOVSIG=GLOBAL(PSOVDFD1,0) I PSOVSIG'="" D
 .I $G(RES)'="" S RES=RES_PSOVSIG
 .E  S RES=PSOVSIG
 G SSET10X
SSETQX I $G(RES)="" Q RES
 S RES=$$REPL^PSOVDF1(RES)
 S RES=RES_SEPC_SEPC_L
 Q RES
 ;
 Q
