ABME8L11 ; IHS/ASDST/DMJ - Header 
 ;;2.6;IHS 3P BILLING SYSTEM;;NOV 12, 2009
 ;Header Segments
 ;
START ;START HERE
 D ^ABME8SE
 D WR^ABMUTL8("SE")
 D ^ABME8GE
 D WR^ABMUTL8("GE")
 D ^ABME8IEA
 D WR^ABMUTL8("IEA")
 Q
