ABME8L1 ; IHS/ASDST/DMJ - Header 
 ;;2.6;IHS 3P BILLING SYSTEM;;NOV 12, 2009
 ;Header Segments
 ;
START ;START HERE
 S ABMSTOT=0
 D ^ABME8ISA
 D WR^ABMUTL8("ISA")
 D ^ABME8GS
 D WR^ABMUTL8("GS")
 D ^ABME8ST
 D WR^ABMUTL8("ST")
 D ^ABME8BHT
 D WR^ABMUTL8("BHT")
 D EP^ABME8REF(87)
 D WR^ABMUTL8("REF")
 D EP^ABME8NM1(41)
 D WR^ABMUTL8("NM1")
 D ^ABME8PER
 D WR^ABMUTL8("PER")
 D EP^ABME8NM1(40)
 D WR^ABMUTL8("NM1")
 Q
