BITX ;IHS/CMI/MWR - ROUTINES TO CREATE FLU AND PNEUMO RISK TAXONOMIES; MAY 10, 2010
 ;;8.4;IMMUNIZATION;;MAY 10,2010
 ;;* MICHAEL REMILLARD, DDS * CIMARRON MEDICAL INFORMATICS, FOR IHS *
 ;;IHS/CMI/LAB-CREATED BY ^ATXSTX ON FEB 03, 2010.
 ;
 ; See referenced routines to see taxonomies being loaded.
 ;
START ;
 D ^BITXA ;     BI HIGH RISK FLU
 D ^BITXB ;     BI HIGH RISK PNEUMO
 D ^BITXC ;     BI HIGH RISK PNEUMO W/SMOKING
 Q
