LRAPAUPT ;AVAMC/REG/WTY - AUTOPSY PRINT ;9/25/00
 ;;5.2T9;LR;**72,248,1018**;Nov 17, 2004
 ;
 S:$G(LREND) LREND=0
 S LRDICS="AU" D ^LRAP G:'$D(Y) END
 S LR("AU1")=1,LRAPX=3 D XR^LRU,EN2^LRUA,SGL^LRAURPT
 I '$G(POP),'$D(ZTSK),LR("AU1")=1,LRDFN>0 D
 .D EN^LRAPAUSR
 .W:IOST'?1"C".E&($E(IOST,1,2)'="P-"!($D(LR("FORM")))) @IOF
END D V^LRU,END^LRUTL
 Q
