ONCOPMP ;Hines OIFO/GWB - PRINTS for MULTIPLE ABSTRACTS ;12/16/99
 ;;2.11;ONCOLOGY;**13,23,25,39**;Mar 07, 1995
 ;
PRT1 ;SEER ABSTRACT
 K DXS S DIOEND="S DN=1,D0=ONCODA F XI=2:1:4 K DXS D @(""^ONCOXA""_XI)"
 S FLDS="[ONCOXA1]",(FR,TO)=NUMBER,BY="@NUMBER",DIC="^ONCO(165.5,",L=0 D EN1^DIP
 Q
P ;
PRT2 ;SET VARIABLES AND @PRINT
 K DXS S DIOEND="S DN=1,D0=ONCODA F XI=50:1:58 K DXS D @(""^ONCOY""_XI)"
 S FLDS="[ONCOY49]",FR=NUMBER,TO=NUMBER,BY="@NUMBER",DIC="^ONCO(165.5,",L=0 D EN1^DIP
 Q
PRT3 ;Report 3
 S ONCOIEN=ONCODA D MULT^ONCOPA1
 ; K DXS S DIOEND="S DN=1,D0=ONCODA F XI=2:1:11 K DXS D @(""^ONCOX""_XI) K DXS"
 ; S FLDS="[ONCOX1]",FR=NUMBER,TO=NUMBER,BY="@NUMBER",DIC="^ONCO(165.5,",L=0 D EN1^DIP
 Q
 ;
PRT4 ;Report 4
 N XD0
 S FLDS="[ONCO XINCIDENCE RPRT]",(FR,TO)=NUMBER,BY="@NUMBER",DIC="^ONCO(165.5,",L=0 D EN1^DIP
 Q
 ;
QA ;QA FORUM
 ;S XDA=$O(^ONCO(160.2,"B","10% QA REPORT-1",0))
1 S DIWF="^ONCO(160.2,1,1,",DIWF(1)="160.1"
 S BY="NUMBER"
 S (FR,TO)=$O(^ONCO(160.1,"C",DUZ(2),0))
 I FR="" S (FR,TO)=$O(^ONCO(160.1,0))
 S TMPIO=IO W !! D EN2^DIWF S IO=TMPIO,IOP=ONCOION D ^%ZIS
 Q:ONCOQ<5  ;S XDA=$O(^ONCO(160.2,"B","10% QA REPORT-2",0)),IOP=ONCOION
2 S IOP=ONCOION
 S DIWF="^ONCO(160.2,2,1,",DIWF(1)="160.1"
 S BY="NUMBER"
 S (FR,TO)=$O(^ONCO(160.1,"C",DUZ(2),0))
 I FR="" S (FR,TO)=$O(^ONCO(160.1,0))
 S TMPIO=IO W !! D EN2^DIWF S IO=TMPIO,IOP=ONCOION D ^%ZIS
 Q
 ;
 ; NEW QA FORM
8 S DIWF="^ONCO(160.2,8,1,",DIWF(1)="165.5",BY="NUMBER",(FR,TO)=ONCODA S TMPIO=IO W !! D EN2^DIWF S IO=TMPIO,IOP=ONCOION D ^%ZIS
 Q
 ;
CK ;Check entry TO PREVENT DELETION
 I DUZ=231,DUZ(2)=10688 Q  ;    package developer can kill
 I DA>3 K ^ONCO(160.2,"B",$E(X,1,30),DA) Q
 W !!?5,"CANNOT DELETE THIS ENTRY" ;TO prevent deletion of exported entries.
H G ^XUSCLEAN ;HALT
 Q
EX ;EXIT
 K DIC,DIR,ONCOXD0,ONCOXD1,ONCOS,DIOEND,FR,TO,BY,L,^TMP("ONCO",$J)
 D ^%ZISC
 Q
