ORWGAPIX ; SLC/STAFF - Graph External Calls ;2/22/06  09:03
 ;;3.0;ORDER ENTRY/RESULTS REPORTING;**215**;Dec 17, 1997
 ;
DATE(X) ; $$(date/time) -> date/time
 N Y D ^%DT
 Q Y
ENDIQ1(RESULTS,DIC,DR,DA,DIQ) ; use file # for DIC
 N NUMDIC K RESULTS,^UTILITY("DIQ1",$J)
 Q:'$G(DIC)  Q:'$L(DR)  Q:'$G(DA)
 S NUMDIC=DIC
 D EN^DIQ1
 M RESULTS=^UTILITY("DIQ1",$J,NUMDIC,DA)
 K ^UTILITY("DIQ1",$J)
 Q
EXT(Y,FILE,FIELD) ; $$(value,file,field) -> external value
 N C S C=$P($G(^DD(FILE,FIELD,0)),U,2) D Y^DIQ
 Q Y
EXTERNAL(FILE,FIELD,FLAG,VAL) ; $$(file,field,flag,internal value) -> external value
 Q $$EXTERNAL^DILFD(FILE,FIELD,FLAG,VAL)
EXTNAME(IEN,FN) ; $$(ien,file#) -> external form of pointer
 N REF
 S REF=$G(^DIC(FN,0,"GL"))
 I $L(REF),+IEN Q $P($G(@(REF_IEN_",0)")),U)
 Q ""
FILENM(FILENUM) ; $$(file#) -> file name
 N DIC,DO,NAME K DIC,DO
 S FILENUM=$$GBLREF(+$G(FILENUM))
 I '$L($G(FILENUM)) Q ""
 S DIC=FILENUM
 D DO^DIC1
 S NAME=$P(DO,U)
 Q NAME
GETDATA(RESULTS,DIC,DR,DA,DIQ) ; use file # for DIC
 N NUMDIC K RESULTS,^UTILITY("DIQ1",$J)
 Q:'$G(DIC)  Q:'$L(DR)  Q:'$G(DA)
 S NUMDIC=DIC
 D EN^DIQ1
 M RESULTS=^UTILITY("DIQ1",$J,NUMDIC,DA)
 K ^UTILITY("DIQ1",$J)
 Q
GBLREF(FILENUM) ; $$(file#) -> global reference
 I '$G(FILENUM) Q ""
 Q $$ROOT^DILFD(+FILENUM)
INDEX(DIK,DA) ; index entry in file   -  from ORWGAPIP
 D IX1^DIK
 Q
XDEL(ENTITY,PARAM,NAME,ORERR) ; from ORWGAPIP
 D DEL^XPAR(ENTITY,PARAM,NAME,.ORERR)
 Q
XEN(ENTITY,PARAM,NAME,ORVAL,ORERR) ; from ORWGAPIP
 D EN^XPAR(ENTITY,PARAM,NAME,.ORVAL,.ORERR)
 Q
XGET(ENTITY,PARAM,INST,FORMAT) ; $$(...) -> parameter values
 Q $$GET^XPAR(ENTITY,PARAM,INST,FORMAT)
XGETLST(ORLIST,ENTITY,PARAM) ; from ORWGAPIP
 D GETLST^XPAR(.ORLIST,ENTITY,PARAM)
 Q
XGETLST1(ORLIST,ENTITY,PARAM,FORMAT,ORERR) ; from ORWGAPIP
 D GETLST^XPAR(.ORLIST,ENTITY,PARAM,FORMAT,.ORERR)
 Q
XGETWP(ORWP,ENTITY,PARAM,ALL) ; from ORWGAPIP
 D GETWP^XPAR(.ORWP,ENTITY,PARAM,ALL)
 Q
 ; kernel functions
FMADD(X,D,H,M,S) ;
 Q $$FMADD^XLFDT(X,$G(D),$G(H),$G(M),$G(S))
NOW() ;
 Q $$NOW^XLFDT
LOW(X) ;
 Q $$LOW^XLFSTR(X)
TRIM(X,F,V) ;
 Q $$TRIM^XLFSTR(X,$G(F,"LR"),$G(V," "))
UP(X) ;
 Q $$UP^XLFSTR(X)
INSIG(NODE) ; $$(node) -> sig ; replace INSIG^ORWGAPIA with this code in v27
 N SIG,SUB,VALUES K VALUES
 S SUB=$P($G(NODE),";",2)
 D RXIN^ORWGAPIA(NODE,.VALUES)
 S SIG=""
 I SUB=5 D
 . S SIG="  Give: "_$G(VALUES("MR"))
 . S SIG=SIG_" "_$P($G(VALUES("SCH",1,0)),U)
 . S SIG=SIG_" "_$P($G(VALUES("SCH",1,0)),U,2)
 I SUB="IV" D
 . S SIG="  Give: "_$G(VALUES("DO"))
 . S SIG=SIG_" "_$$EXT^ORWGAPIX($G(VALUES("START")),55.01,.02)
 . S SIG=SIG_" "_$G(VALUES("SCH",1,0))
 Q SIG
