DVBHCE28 ; ;04/10/06
 S X=DE(17),DIC=DIE
 K ^DPT("ASX",$E(X,1,30),DA)
 S X=DE(17),DIC=DIE
 D EVENT^IVMPLOG(DA)
 S X=DE(17),DIC=DIE
 S IVMX=X,IVMKILL=2,X="IVMPXFR" X ^%ZOSF("TEST") D:$T DPT^IVMPXFR S X=IVMX K IVMX,IVMKILL
 S X=DE(17),DIC=DIE
 I ($T(AVAFC^VAFCDD01)'="") S VAFCF=".02;" D AVAFC^VAFCDD01(DA)
 S X=DE(17),DIC=DIE
 D:($T(ADGRU^DGRUDD01)'="") ADGRU^DGRUDD01(DA)
 S X=DE(17),DIIX=2_U_DIFLD D AUDIT^DIET
